### ISSUE TITLE
RPM for togo 3.0-4 cannot be installed on CentOS 7

### ISSUE THREAD

**Issue by stevemeier** [genereese/togo#40] opened 2021-11-19 21:14 UTC
Hello,

I just wanted to update `togo` on my CentOS build-system, but `yum` failed as follows:

```
[root@buildhorst ~]# LC_ALL=C yum install https://github.com/genereese/togo/releases/download/v3.0r4/togo-3.0-4.noarch.rpm
Loaded plugins: fastestmirror
togo-3.0-4.noarch.rpm                                                                                   |  17 kB  00:00:00
Examining /var/tmp/yum-root-BcAsWf/togo-3.0-4.noarch.rpm: togo-3.0-4.noarch
Marking /var/tmp/yum-root-BcAsWf/togo-3.0-4.noarch.rpm as an update to togo-2.5-1.noarch
Resolving Dependencies
--> Running transaction check
---> Package togo.noarch 0:2.5-1 will be updated
---> Package togo.noarch 0:3.0-4 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

===============================================================================================================================
 Package                  Arch                       Version                      Repository                              Size
===============================================================================================================================
Updating:
 togo                     noarch                     3.0-4                        /togo-3.0-4.noarch                      46 k

Transaction Summary
===============================================================================================================================
Upgrade  1 Package

Total size: 46 k
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
ERROR You need to update rpm to handle:
rpmlib(PayloadIsZstd) <= 5.4.18-1 is needed by togo-3.0-4.noarch
RPM needs to be updated
 You could try running: rpm -Va --nofiles --nodigest
Your transaction was saved, rerun it with:
 yum load-transaction /tmp/yum_save_tx.2021-11-19.16-09.EUFOvO.yumtx
```

According to this Red Hat Bugzilla entry (https://bugzilla.redhat.com/show_bug.cgi?id=1823142) zstd payloads are only supported on RHEL/CentOS 8.2 and newer. This unfortunately makes it impossible to install on RHEL/CentOS 7.x.

**Comment by genereese** [comment] 2021-11-20 02:28
Though I can not test this because I don't have access to my workstation at the moment, it is likely caused by the compression level of the RPM.

You can fix this with a custom build of the Togo RPM from source.

`$ git clone https://github.com/genereese/togo.git
$ cd togo
$ vim ./spec/header`

Change the following line:

`Source0: %{name}.tar.gz`

-to:

`Source0: %{name}.tar`

-then save and build Togo.

$./build-togo.sh
$ sudo yum localinstall ./rpms/*.rpm`

The resulting RPM will not use any zlib compression and should be able to be installed.

**Comment by stevemeier** [comment] 2021-11-20 21:29
Thanks, but isn't the point of releases to make the software as simply to deploy as possible?
CentOS 7 has a good 2.5 years left in it, so I feel like releases should support it.

**Comment by genereese** [comment] 2021-11-21 08:53
While I don't immediately see an issue with disabling compression of such a small RPM, literally every other Togo user since the release of the software (8 years ago) has deployed it with compression of the RPM enabled.

As this is the first time in those 8 years that this issue has been reported, changing the entire RPM to satisfy the requirements of a single user must be weighed against the possibility of negatively affecting any of the previous 8 years of users via such a change.

I haven't been able to even test the fix to confirm that it does work and I don't feel comfortable making the change to the default package until I have more time to research the potential issues that change could create.

For now, please consider the workaround I have proposed and let me know if it fixes the issue for you. It is literally just the deletion of 3 characters from the spec header to disable compression for the RPM.

If it does fix the issue for you, then I will set aside some time to make sure that setting that as the default will not cause more problems than it fixes.

**Comment by genereese** [comment] 2021-11-25 04:17
Any word on if this fix works or not?

As a reminder; this is open-source software written in my spare time, provided to users for free. I do not have unlimited time/funds to devote to every potential test system out there.

If you would like this issue addressed, I will need your help.

**Comment by stevemeier** [comment] 2021-11-27 23:15
That does not seem to work on CentOS 7 unfortunately.

The `python3-sqlobject` package is not available on C7, so `build-togo.sh` does not run.
There is only a `python-sqlobject` package but that is installed and seems to be for Python 2.x

**Comment by genereese** [comment] 2021-11-28 03:33
Thanks for the update.

Togo version 3 and above were all re-written to use python 3 instead of python 2. If you are unable to find a version of python3-sqlobject (and, obviously, python3 - if it's not installed), Togo version 3 and above will not be able to run on that system regardless of the compression fix.

You can still use Togo 2.x, but it lacks any of the recent updates and fixes that have been applied to Togo.

Do you want me to leave this issue open so that you can test getting python3-sqlobject on that system? -or should I close it?

**Closed** 2021-12-04 17:31 UTC

**Comment by Tqnsls** [comment] 2025-03-04 10:41
Hi Gene,
I just stumbled over this problem because unfortunately we still need to maintain RHEL7 servers. I was able to resolve this issue by
adding
`%define _source_payload w0.gzdio`
`%define _binary_payload w0.gzdio`
just above the line containing `%define debug_package %{nil}` to the `spec/header` and build a new package.
On my RHEL9 building machine all previous packages were compressed as `zsdt`, now it is `gzip`.

Source I used as inspiration: https://stackoverflow.com/a/10255406
I thought maybe you would like to know or anyone else how stumble(s|d) over this kind of problem
