### ISSUE TITLE
error: Installed (but unpackaged) file(s) found:

### ISSUE THREAD

**Issue by erikmathis** [genereese/togo#9] opened 2015-02-10 01:22 UTC
I'm getting this error and I'm not sure why

Checking for unpackaged file(s): /usr/lib/rpm/check-files /home/emathis/e/node/meta/redhat/BUILDROOT/node-0.10.36-2.x86_64
error: Installed (but unpackaged) file(s) found:
   /usr/lib/node_modules/npm/node_modules/node-gyp/gyp/PRESUBMIT.pyc
   /usr/lib/node_modules/npm/node_modules/node-gyp/gyp/PRESUBMIT.pyo
....

no RPM is built.  I guess I'm not sure what a "unpackaged" file is.

**Comment by genereese** [comment] 2015-03-12 07:47
If you can provide me with the steps to reproduce this error, I'll be happy to take a look at it. I can't seem to reproduce what you're reporting.

**Comment by genereese** [comment] 2015-05-21 19:37
Going to go ahead and close this issue. If you are still having problems with it, please open a new issue and I'll look into it.

**Comment by genereese** [comment] 2015-05-25 15:56
Re-opening this issue. The problem is that when you attempt to package python files, a python bytecompile script is automatically run during the packaging process. This creates the bytecompiled versions of your python source (the *.pyc and *.pyo files).

Since these files are created during the build process, they pollute the RPM source with extra files that it wasn't expecting; hence the "unpackaged files" error.

I'll need to put in a special case for handling python files and will push it out with the next release.

**Comment by genereese** [comment] 2015-05-25 17:02
Ok, this should now be fixed.

Togo will now handle byte-compiling any python 2.7 files it finds before RPM creation so that they are added to the final RPM properly.

This fix probably does not properly handle python3, but I won't spend the time to add the support yet unless someone requests it.

**Closed by genereese** 2015-05-25 17:02 UTC

**Comment by LukeLIN-web** [comment] 2023-09-09 13:13
In my case, I use `%{python3_sitelib}/* ` to add all files.
